version: '3.9'
services:
  twikoo:
    image: llnancy/twikoo:latest
    restart: always
    container_name: twikoo
    environment:
      TZ: Asia/Shanghai
      # IP 请求限流，当同一 IP 短时间内请求次数超过阈值将对该 IP 返回错误
      TWIKOO_THROTTLE: 251
      # 为 true 时只监听本地请求，使得 nginx 等服务器反代之后不暴露原始端口
      TWIKOO_LOCALHOST_ONLY: true
      # 在一些特殊情况下使用，如使用了 CloudFlare CDN 它会将请求 IP 写到请求头的 cf-connecting-ip 字段上
      TWIKOO_IP_HEADERS: ['headers.cf-connecting-ip']
    volumes:
      - /home/sunchaser/twikoo/data:/app/data
    ports:
      - 8080:8080
# 如果没有创建过网络则注释掉下面的内容，docker 会默认会创建出一个网络。
networks:
  default:
    external:
      name: nginx_front