version: '3.9'

services:
  # Twikoo 主服务
  twikoo-service:
    image: sunchaserlilu/sunchaser-twikoo:latest
    restart: always
    container_name: twikoo
    environment:
      TZ: Asia/Shanghai
      MONGODB_URI: mongodb://root:B0duEDBW9yFfszd5@twikoo-mongo:27017/
    ports:
      - 8080:8080
  # 数据库，如使用已有数据库，请注释
  twikoo-mongo:
    image: mongo
    restart: always
    container_name: twikoo-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: B0duEDBW9yFfszd5
    volumes:
      - /home/sunchaser/twikoo/data:/data/db
  # 用于浏览器操作数据库，如需，请解除注释
  # twikoo-mongo-express:
  #   image: mongo-express
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: B0duEDBW9yFfszd5
  #     ME_CONFIG_MONGODB_URL: mongodb://root:B0duEDBW9yFfszd5@twikoo-mongo:27017/

# 如果没有创建过网络则注释掉下面的内容，docker会默认会创建出一个网络。
networks:
  default:
    external:
      name: nginx_front