version: '3.9'

services:
  mysql:
    image: mysql:5.7.28
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    # 挂载数据卷
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      # - ./data/mysql:/var/lib/mysql
