version: '3.9'

services:
  redis:
    image: redis:7.0.7-alpine
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server /etc/redis.conf
    # 挂载数据卷
    volumes:
      - ./redis.conf:/etc/redis.conf
      # - /Users/sunchaser/workspace/redis/data:/data
