name: Build Twikoo

on:
  push:
    paths:
      - "twikoo/**"
      - ".github/workflows/twikoo-*.yml"

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get twikoo version
        id: twikoo
        run: |
          echo ::set-output name=version::$(< twikoo/twikoo.version)

      - name: Set Docker image metadata
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: sunchaserlilu/sunchaser-twikoo
          flavor: latest=true
          tags: ${{ steps.twikoo.outputs.version }}
          labels: |
            maintainer=admin@lilu.org.cn
            org.opencontainers.image.version=${{ steps.twikoo.outputs.version }}

      - name: Login in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./twikoo/Dockerfile
          # platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
